title: TB148の博客 #博客标题
description: 一个非常小的Blog #博客描述
keywords: oier,blog #博客关键字

#title hide and show
hide: (つェ⊂)我藏好啦
show: ´∇｀ 呀被发现啦~ 

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "tb148.github.io" # change this to the base hostname & protocol for your site
bulidtime: "1560168492" #博客建立时的时间戳 可进入https://tool.lu/timestamp/将博客建立时的日期转换成时间戳
           #The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

paginate: 10 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background: https://tb148.github.io/pic/pony/wallpaper.jpg
theme_color: DF2D8B

google_analytics:
# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

#install emoji
plugins:
  - jemoji

# social
author: "TB148"
image:
twitter:
  username:
#  site:
facebook:
  #publisher: null
  #profile_id: null
  #app_id: null
  #authors: null
#  admins:
